#!/usr/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# We grep a string of the default DH key, if true we create a DH key for the slapd service
#

if ! /usr/bin/grep -q 'MIIBCAKCAQEAou6/6s7X2gd+i8+' /etc/openldap/certs/slapd.dh.params; then
    exit 0
fi

# fix unable to write 'random state' 
# https://bugzilla.redhat.com/show_bug.cgi?id=1256427
export RANDFILE=$OPENSHIFT_DATA_DIR/.rnd

tmpfile=$(mktemp /tmp/slapd-create-dhparam.XXXXXXX)
trap "/usr/bin/rm -f ${tmpfile}" EXIT

set -e # Exit immediately if any error occurs

/usr/bin/openssl dhparam -out ${tmpfile} 2048
/usr/bin/mv -f ${tmpfile} /etc/openldap/certs/slapd.dh.params
/usr/bin/chown root:ldap /etc/openldap/certs/slapd.dh.params
/usr/bin/chmod 440 /etc/openldap/certs/slapd.dh.params
